# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn test
    - name: Build
      run: mvn install
    - name: Generate JavaDoc
      if: github.ref == 'refs/heads/develop'
      run: mvn javadoc:javadoc
    - name: move doc file
      if: github.ref == 'refs/heads/develop'
      run: |
        rm -rf doc/javadoc
        cp -rf target/site/apidocs/. doc/javadoc
    - name: Tidy up the Javadocs
      if: github.ref == 'refs/heads/develop'
      id: tidy
      uses: cicirello/javadoc-cleanup@v1.2.0
      with:
       path-to-root: doc/javadoc
    - name: Log javadoc-cleanup output
      if: github.ref == 'refs/heads/develop'
      run: |
       echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"
    - name: Commit Documentation Changes
      if: github.ref == 'refs/heads/develop'
      run: |
        if [ $(git status | grep -c "**/*.html") == "0" ]; then
          git checkout .
         else
          git config --global user.name 'amyhcy'
          git config --global user.email 'amy.chuanyanhu@gmail.com'
          git add -A
          git commit -m "Javadoc updates."
        fi
    - name: push
      if: github.ref == 'refs/heads/develop'
      run: |
          git push origin develop
