name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: mvn install
        working-directory: .

      - name: Test
        run: mvn test
        working-directory: .

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
        working-directory: .

      - name: Copy Document to Location
        run: |
          rm -rf doc/javadoc
          cp -rf target/site/apidocs/. doc/javadoc

      - name: Tidy up the Javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1.2.0
        with:
          path-to-root: doc/javadoc

      - name: Log javadoc-cleanup output
        run: |
          echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

      - name: Commit Documentation Changes
        run: |
          if [ $(git status | grep -c "**/*.html") == "0" ]; then
            git checkout .
          else
            git config --global user.name 'parikhalayy'
            git config --global user.email 'parikh.alay58@gmail.com'
            git add -A
            git commit -m "Javadoc updates."
          fi
